/******************************************************************************
* File Name:   main.c
*
* Description: This example demonstrates how to use the Em_EEPROM middleware in
* PSOC™ Control C3M/P8 MCU devices. In this example, a counter is read from the
* emulated EEPROM (Em_EEPROM), incremented, written back to the Em_EEPROM and
* printed on a serial terminal.
*
* Related Document: See README.md
*
*
********************************************************************************
* (c) 2026, Infineon Technologies AG, or an affiliate of Infineon
* Technologies AG. All rights reserved.
* This software, associated documentation and materials ("Software") is
* owned by Infineon Technologies AG or one of its affiliates ("Infineon")
* and is protected by and subject to worldwide patent protection, worldwide
* copyright laws, and international treaty provisions. Therefore, you may use
* this Software only as provided in the license agreement accompanying the
* software package from which you obtained this Software. If no license
* agreement applies, then any use, reproduction, modification, translation, or
* compilation of this Software is prohibited without the express written
* permission of Infineon.
*
* Disclaimer: UNLESS OTHERWISE EXPRESSLY AGREED WITH INFINEON, THIS SOFTWARE
* IS PROVIDED AS-IS, WITH NO WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
* INCLUDING, BUT NOT LIMITED TO, ALL WARRANTIES OF NON-INFRINGEMENT OF
* THIRD-PARTY RIGHTS AND IMPLIED WARRANTIES SUCH AS WARRANTIES OF FITNESS FOR A
* SPECIFIC USE/PURPOSE OR MERCHANTABILITY.
* Infineon reserves the right to make changes to the Software without notice.
* You are responsible for properly designing, programming, and testing the
* functionality and safety of your intended application of the Software, as
* well as complying with any legal requirements related to its use. Infineon
* does not guarantee that the Software will be free from intrusion, data theft
* or loss, or other breaches ("Security Breaches"), and Infineon shall have
* no liability arising out of any Security Breaches. Unless otherwise
* explicitly approved by Infineon, the Software may not be used in any
* application where a failure of the Product or any consequences of the use
* thereof can reasonably be expected to result in personal injury.
*******************************************************************************/

#include "cy_pdl.h"          /* PSoC peripheral driver library (PDL) — HAL/PDL APIs for all on-chip peripherals */
#include "cybsp.h"            /* Board support package — pin/clock configurations generated by Device Configurator */
#include "cy_em_eeprom.h"     /* Em_EEPROM middleware — emulates EEPROM in internal flash */

/*******************************************************************************
* Macros
********************************************************************************/
#define LED_DELAY_MS                (500u)   /* LED toggle period in milliseconds */

/* Logical Size of Emulated EEPROM in bytes */
#define LOGICAL_EM_EEPROM_SIZE      (15u)    /* Total number of bytes used in the EEPROM data region */
#define LOGICAL_EM_EEPROM_START     (0u)     /* Starting byte offset for read/write operations */

/* Location of reset counter in Emulated EEPROM */
/* Bytes 13-14 store the two-digit ASCII reset counter (e.g. '0','0' = 00 up to '9','9' = 99) */
#define RESET_COUNT_LOCATION        (13u)
/* Size of reset counter in bytes (two ASCII digit characters) */
#define RESET_COUNT_SIZE            (2u)

/* ASCII character constants used for counter comparison and initialization */
#define ASCII_NINE                  (0x39)   /* ASCII code for character '9' */
#define ASCII_ZERO                  (0x30)   /* ASCII code for character '0' */
#define ASCII_P                     (0x50)   /* ASCII code for character 'P' — used as a valid-data sentinel */

/*******************************************************************************
* Function Prototypes
********************************************************************************/
void handle_error(uint32_t status, char *message);
void uart_print(char *message);

/*******************************************************************************
* Global Variables
********************************************************************************/
cy_stc_scb_uart_context_t CYBSP_UART_context;  /* UART runtime context structure (maintained by the SCB UART driver) */

cy_stc_eeprom_context_t em_eeprom_context;     /* Em_EEPROM runtime context (maintained by the Em_EEPROM middleware) */

/* Emulated EEPROM configuration structure — values sourced from Device Configurator generated macros.
 * .eepromSize         : logical EEPROM size in bytes (512 bytes).
 * .blockingWrite      : when true, Cy_Em_EEPROM_Write() blocks until the flash row write completes.
 * .redundantCopy      : when true, each logical row is mirrored in a second flash area for data recovery.
 * .wearLevelingFactor : multiplier applied to the physical flash area to spread write wear (factor = 2).
 * .simpleMode         : when false, full wear-levelling and redundancy features are active.
 */
cy_stc_eeprom_config_t em_eeprom_config =
{
    .eepromSize         = srss_0_eeprom_0_SIZE,                /* 512 bytes */
    .blockingWrite      = srss_0_eeprom_0_BLOCKINGMODE,        /* Blocking writes enabled */
    .redundantCopy      = srss_0_eeprom_0_REDUNDANT_COPY,      /* Redundant copy enabled */
    .wearLevelingFactor = srss_0_eeprom_0_WEARLEVELING_FACTOR, /* Wear levelling factor of 2 */
    .simpleMode         = srss_0_eeprom_0_SIMPLEMODE,          /* Simple mode disabled */
};

/* EEPROM storage Emulated EEPROM flash. */
CY_ALIGN(CY_EM_EEPROM_FLASH_SIZEOF_ROW)
const uint8_t em_eeprom_storage[srss_0_eeprom_0_PHYSICAL_SIZE] = {0u};

/* RAM buffer that receives data from Cy_Em_EEPROM_Read(). */
uint8_t em_eeprom_read_array[LOGICAL_EM_EEPROM_SIZE];

/* Default initialization data written to EEPROM on the very first power-up (when no valid data exists).
 * The 15 bytes encode the ASCII string "Power Cycle# 00":
 *   Index:  0     1     2     3     4     5     6     7     8     9    10    11    12    13    14
 *   Char :  'P'   'o'   'w'   'e'   'r'   ' '   'C'   'y'   'c'   'l'   'e'   '#'   ' '   '0'   '0'
 * Bytes 13-14 hold the two-digit ASCII reset counter that is incremented on every subsequent boot.
 */
uint8_t em_eeprom_write_array[LOGICAL_EM_EEPROM_SIZE] = { 0x50, 0x6F, 0x77, 0x65, 0x72, 0x20, 0x43, 0x79, 0x63, 0x6C, 0x65, 0x23, 0x20, 0x30, 0x30};
                                                              /* P       o         w         e         r         C         y          c         l        e        #           0     0 */

/********************************************************************************
* Function Name: main
*********************************************************************************
* Summary:
* The main function performs the following actions:
*  1. Initializes the BSP
*  2. Calls the functions to configure and initialize retarget IO and Emulated
*     EEPROM
*  3. Reads the Emulated EEPROM content if available
*  4. Increments the Emulated EEPROM content by one and writes the new content
*     back to Emulated EEPROM
*  5. Toggles the LED once every 0.5 seconds if the Emulated EEPROM read and
*     write operations were successful
*
********************************************************************************/
int main(void)
{
    cy_rslt_t result;                             /* General BSP/PDL result code */
    cy_en_em_eeprom_status_t em_eeprom_status;     /* Return status of every Em_EEPROM API call */
    cy_en_scb_uart_status_t uart_status;           /* Return status of the SCB UART initialization */
    uint32_t int_status;                           /* Saved interrupt mask for critical-section protection */
    int count;                                     /* Loop index for printing EEPROM contents via UART */
    char em_eeprom_char;                           /* Single byte read from the EEPROM read buffer */

    /* Initialize the device and board peripherals */
    result = cybsp_init() ;
    if (result != CY_RSLT_SUCCESS)
    {
        CY_ASSERT(0);  /* Halt execution — peripheral initialization failed */
    }

    /* Enable global interrupts now that BSP initialization is complete */
    __enable_irq();

    /* Initialize the SCB block configured as UART using Device Configurator generated config */
    uart_status = Cy_SCB_UART_Init(CYBSP_UART_HW, &CYBSP_UART_config, &CYBSP_UART_context);
    if(uart_status != CY_SCB_UART_SUCCESS)
    {
        /* UART initialization failed — halt execution */
        CY_ASSERT(0);
    }

    /* Enable the UART hardware block to start transmitting/receiving */
    Cy_SCB_UART_Enable(CYBSP_UART_HW);

    /* \x1b[2J\x1b[;H - ANSI ESC sequence to clear screen */
    uart_print("\x1b[2J\x1b[;H");
    uart_print("************************************************************\r\n");
    uart_print("PSOC Control C3M/P8: Emulated EEPROM\r\n");
    uart_print("************************************************************\r\n\n");

    /* Provide the physical flash address to the middleware — must be set at run-time
     * because the linker assigns the final address of em_eeprom_storage.
     */
    em_eeprom_config.userFlashStartAddr = (uint32_t) em_eeprom_storage;

    /* Initialize Emulated EEPROM */
    em_eeprom_status = Cy_Em_EEPROM_Init(&em_eeprom_config, &em_eeprom_context);
    handle_error(em_eeprom_status, "Emulated EEPROM Initialization Error \r\n");

    /* Read 15 bytes out of Emulated EEPROM memory */
    em_eeprom_status = Cy_Em_EEPROM_Read(LOGICAL_EM_EEPROM_START, em_eeprom_read_array,
                                            LOGICAL_EM_EEPROM_SIZE, &em_eeprom_context);
    handle_error(em_eeprom_status, "Emulated EEPROM Read failed \r\n");

    /* Check the sentinel byte at index 0.
     * A value of 'P' (ASCII_P) means the EEPROM has been previously initialized.
     * Any other value (e.g. 0xFF after chip erase) triggers a fresh initialization.
     */
    if(ASCII_P != em_eeprom_read_array[0])
    {
        /* --- First power-up path: EEPROM contains no valid data --- */

        /* Disable interrupts while modifying flash to prevent a context switch
         * or ISR from corrupting an in-progress flash erase/write sequence.
         */
        int_status = Cy_SysLib_EnterCriticalSection();

        /* Erase all logical EEPROM rows before writing fresh data */
        em_eeprom_status = Cy_Em_EEPROM_Erase(&em_eeprom_context);
        handle_error(em_eeprom_status, "Emulated EEPROM erase failed \r\n");

        /* Write the default "Power Cycle# 00" string (em_eeprom_write_array) starting
         * at logical address 0, covering all 15 bytes.
         */
        em_eeprom_status = Cy_Em_EEPROM_Write(LOGICAL_EM_EEPROM_START,
                                                 em_eeprom_write_array,
                                                 LOGICAL_EM_EEPROM_SIZE,
                                                 &em_eeprom_context);

        /* Restore the previous interrupt state — flash operation complete */
        Cy_SysLib_ExitCriticalSection(int_status);

        handle_error(em_eeprom_status, "Emulated EEPROM Write failed \r\n");
    }
    else
    {
        /* The Emulated EEPROM content is valid. Increment Counter by 1 */
        em_eeprom_read_array[RESET_COUNT_LOCATION + 1]++;

        /* Handle ASCII digit carry-over (units overflow: '9' -> '0', tens digit += 1) */
        if(em_eeprom_read_array[RESET_COUNT_LOCATION + 1] > ASCII_NINE)
        {
            /* Reset units digit back to '0' */
            em_eeprom_read_array[RESET_COUNT_LOCATION + 1] = ASCII_ZERO;

            /* Carry: increment the tens (upper) ASCII digit */
            em_eeprom_read_array[RESET_COUNT_LOCATION]++;

            /* Clamp the counter at maximum value "99" — do not wrap around */
            if(em_eeprom_read_array[RESET_COUNT_LOCATION] > ASCII_NINE)
            {
                em_eeprom_read_array[RESET_COUNT_LOCATION]     = ASCII_NINE;  /* tens digit = '9' */
                em_eeprom_read_array[RESET_COUNT_LOCATION + 1] = ASCII_NINE;  /* units digit = '9' */
            }
        }

        /* Disable interrupts before flash write to ensure atomicity */
        int_status = Cy_SysLib_EnterCriticalSection();

        /* Write only the 2-byte counter field back to EEPROM — avoids unnecessary
         * wear on the other bytes that have not changed.
         */
        em_eeprom_status = Cy_Em_EEPROM_Write(RESET_COUNT_LOCATION,
                                                 &em_eeprom_read_array[RESET_COUNT_LOCATION],
                                                 RESET_COUNT_SIZE,
                                                 &em_eeprom_context);

        /* Re-enable interrupts after flash write is complete */
        Cy_SysLib_ExitCriticalSection(int_status);

        handle_error(em_eeprom_status, "Emulated EEPROM Write failed \r\n");
    }

    /* Read back the EEPROM contents after the write to verify what was stored and
     * to obtain the updated counter value for display on the terminal.
     */
    em_eeprom_status = Cy_Em_EEPROM_Read(LOGICAL_EM_EEPROM_START,
                                            em_eeprom_read_array, LOGICAL_EM_EEPROM_SIZE,
                                            &em_eeprom_context);
    handle_error(em_eeprom_status, "Emulated EEPROM Read failed \r\n" );

    for(count = 0; count < LOGICAL_EM_EEPROM_SIZE; count++)
    {
        em_eeprom_char = em_eeprom_read_array[count];  /* Fetch one ASCII character */
        Cy_SCB_Write(CYBSP_UART_HW, em_eeprom_char);  /* Transmit it over UART */
    }
    uart_print("\r\n");  /* Move terminal cursor to next line after the EEPROM string */

    /* Main application loop — blink USER_LED1 at 1 Hz (500 ms on, 500 ms off) to
     * indicate that the EEPROM read/write sequence completed successfully.
     */
    for (;;)
    {
        /* Toggle the user LED state (on -> off or off -> on) */
        Cy_GPIO_Inv(CYBSP_USER_LED1_PORT, CYBSP_USER_LED1_PIN);

        /* Block for LED_DELAY_MS milliseconds before next toggle */
        Cy_SysLib_Delay(LED_DELAY_MS);
    }
}

/********************************************************************************
* Function Name: handle_error
*********************************************************************************
* Summary:
* This function processes unrecoverable errors such as any component
* initialization errors etc. In case of such error the system will
* stay in the infinite loop of this function.
*
* Parameters:
*  uint32_t status: contains the status.
*  char* message: contains the message that is printed to the serial terminal.
*
* Note:
*  If error occurs interrupts are disabled.
*
********************************************************************************/
void handle_error(uint32_t status, char *message)
{
    if(CY_EM_EEPROM_SUCCESS != status)
    {
        /* Distinguish between a fatal error and the recoverable redundant-copy condition */
        if(CY_EM_EEPROM_REDUNDANT_COPY_USED != status)
        {
            Cy_GPIO_Write(CYBSP_USER_LED1_PORT, CYBSP_USER_LED1_PIN, CYBSP_LED_STATE_ON);
            __disable_irq();  /* Halt all interrupt-driven activity */

            if(NULL != message)
            {
                uart_print(message);  /* Print the caller-supplied error description */
            }

            while(1u);  /* Infinite loop — only a hardware reset can recover from here */
        }
        else
        {
            /* Non-fatal: the primary EEPROM copy is corrupted but the redundant
             * copy was successfully used to satisfy the read. Notify the user via UART
             * and continue normal operation.
             */
            uart_print("Main copy is corrupted. Redundant copy in Emulated EEPROM is used \r\n");
        }
    }
}

/********************************************************************************
* Function Name: uart_print
*********************************************************************************
* Summary:
* This function prints the message to the serial terminal
*
* Parameters:
*  char* message: message that is printed to the serial terminal.
*
********************************************************************************/
void uart_print(char *message)
{
    if(NULL != message)  /* Guard against NULL pointer — Cy_SCB_UART_PutString has no NULL check */
    {
        /* Transmit the null-terminated string over the configured UART hardware block.
         * This call is blocking; it returns only after all bytes are placed in the TX FIFO.
         */
        Cy_SCB_UART_PutString(CYBSP_UART_HW, message);
    }
}

/* [] END OF FILE */
